### PR TITLE
removing tinyxml from graspit src

### PR DESCRIPTION
**Pull request by jvarley**
removed tinyxml from graspit src

### CODE REVIEW

**Comment by JenniferBuehler** [comment]
Ok so you've instead removed the graspit-tinyxml dependency incl. sources from graspit altogether, if that works with the original source, that's a good idea.

Shall I merge these changes or should we use the removal from catkin_depends as in my last commit?

**Comment by jvarley** [comment]
I think I like your change better actually.  Its less invasive.

**Comment by jvarley** [comment]
maybe in the future we could remove tinyxml and qhull from src, but no reason to do it for the conversion to cmake pr.

**Comment by JenniferBuehler** [comment]
Ok, I'll leave this pull request then, and we'll keep the change in my other commit.

**Pull request closed without merging**
